function el_fs_recon_all(config, pat)

orig_mgz = fullfile(pat.t1.orig_dir, '001.mgz');

bash_code = sprintf( ...
    ['%s; ' ...
    'mri_convert %s %s; ' ...
    'recon-all -s %s -all'], ...
    fs_setup_code(config), ...
    pat.t1.deface, orig_mgz, ...
    pat.name);

system(bash_code);

end